# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: /
    weight: 10
  # - name: Projects
    # url: '#projects'
    # weight: 30
  - name: Publications
    url: '/#publications'
    weight: 50
  - name: Posts
    url: '#posts'
    weight: 60
  - name: Talks
    url: '/#talks'
    weight: 70
  - name: Education
    url: 'education/'
    weight: 80
  - name: Experience
    url: 'experience/'
    weight: 90
  - name: Curriculum vitae
    url: uploads/resume_mini.pdf
    weight: 99
